name: AzureReactCloud

on:
  push:
    branches:
      - master

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: 19218edb-1037-4857-a70a-9945ca909ad1
  NODE_VERSION: '14.21.3'

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: Deploy to production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Verify Node.js version
        run: node --version

      - name: List directory contents
        run: ls -la

      - name: Change to coursesApp directory
        run: cd coursesApp

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to production with artifact
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: skillsphere-app
          app-name: react-app
          use-staging-deployment: false
          package: './build'
